server:
  port: 8080  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ShopApp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      #chỗ này mà sửa thành drop-create thì rất nguy hiểm, nó sẽ xóa hết dữ liệu trong database
      #ddl-auto: validate
      #Hibernate sẽ không tạo, sửa đổi hoặc xóa bất kỳ bảng, cột hay ràng buộc nào trong cơ sở dữ liệu
      #validate thường được sử dụng trong môi trường production
      #Nếu có sự khác biệt giữa cấu trúc cơ sở dữ liệu và các entity class
      #lỗi sẽ được hiển thị và yêu cầu sửa đổi cấu trúc cơ sở dữ liệu một cách thủ công
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
    prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: i5jZU8Zkw8b8Nz20JHORnRjN2lIpCPGzk6IF/yg0h3c=

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# http://localhost:8080/swagger-ui/index.html

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health"